/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import costum.GradientPanel;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import theme.FlatLafManager;
/**
 *
 * @author User
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnkiri = new costum.GradientPanel();
        jLabel1 = new javax.swing.JLabel();
        pnkanan = new javax.swing.JPanel();
        pnDasar = new javax.swing.JPanel();
        pnUtama = new javax.swing.JPanel();
        gradientPanelHorizontal1 = new costum.GradientPanelHorizontal();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnkiri.setForeground(new java.awt.Color(30, 32, 30));
        pnkiri.setColor1(new java.awt.Color(139, 69, 19));
        pnkiri.setColor2(new java.awt.Color(139, 69, 19));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Logo");

        javax.swing.GroupLayout pnkiriLayout = new javax.swing.GroupLayout(pnkiri);
        pnkiri.setLayout(pnkiriLayout);
        pnkiriLayout.setHorizontalGroup(
            pnkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnkiriLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        pnkiriLayout.setVerticalGroup(
            pnkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnkiriLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(610, Short.MAX_VALUE))
        );

        getContentPane().add(pnkiri, java.awt.BorderLayout.LINE_START);

        pnkanan.setBackground(new java.awt.Color(255, 255, 255));
        pnkanan.setLayout(new java.awt.BorderLayout());

        pnDasar.setBackground(new java.awt.Color(250, 250, 250));

        pnUtama.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnUtamaLayout = new javax.swing.GroupLayout(pnUtama);
        pnUtama.setLayout(pnUtamaLayout);
        pnUtamaLayout.setHorizontalGroup(
            pnUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        pnUtamaLayout.setVerticalGroup(
            pnUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        gradientPanelHorizontal1.setColor1(new java.awt.Color(139, 69, 19));
        gradientPanelHorizontal1.setColor2(new java.awt.Color(245, 222, 179));

        javax.swing.GroupLayout gradientPanelHorizontal1Layout = new javax.swing.GroupLayout(gradientPanelHorizontal1);
        gradientPanelHorizontal1.setLayout(gradientPanelHorizontal1Layout);
        gradientPanelHorizontal1Layout.setHorizontalGroup(
            gradientPanelHorizontal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        gradientPanelHorizontal1Layout.setVerticalGroup(
            gradientPanelHorizontal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnDasarLayout = new javax.swing.GroupLayout(pnDasar);
        pnDasar.setLayout(pnDasarLayout);
        pnDasarLayout.setHorizontalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(gradientPanelHorizontal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnDasarLayout.setVerticalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDasarLayout.createSequentialGroup()
                .addComponent(gradientPanelHorizontal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pnUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pnkanan.add(pnDasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnkanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         // Terapkan tema FlatLaf
    FlatLafManager.applyFlatLaf();

    // Jalankan aplikasi
    SwingUtilities.invokeLater(() -> {
        new MenuUtama().setVisible(true);
    });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private costum.GradientPanelHorizontal gradientPanelHorizontal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnDasar;
    private javax.swing.JPanel pnUtama;
    private javax.swing.JPanel pnkanan;
    private costum.GradientPanel pnkiri;
    // End of variables declaration//GEN-END:variables
}
