
package view.Kue;

import costum.LabelGambar;

/**
 *
 * @author User
 */
public class KueView extends javax.swing.JPanel {

    /**
     * Creates new form KueView
     */
    public KueView() {
    initComponents();

        // Menggunakan layout null untuk kontrol manual
        this.setLayout(null);  // Tidak ada layout manager, kontrol posisi manual

        // Membuat LabelGambar dan menambahkan ke panel
        // Menggunakan path relatif untuk gambar yang ada di dalam folder img
        LabelGambar labelGambar = new LabelGambar("img/kueView.png");  // Path gambar sesuai dengan tempat Anda menyimpan gambar
        labelGambar.setBounds(50, 50, 794, 526);  // Tentukan posisi dan ukuran gambar
        this.add(labelGambar);  // Menambahkan label gambar ke panel

        // Menentukan ukuran panel
        this.setPreferredSize(new java.awt.Dimension(794, 526));  // Ukuran panel sesuai dengan gambar
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
