
package view.Kue;

import costum.LabelGambar;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class KueView extends javax.swing.JPanel {

    /**
     * Creates new form KueView
     */
    public KueView() {
  initComponents();
        
        // Menggunakan layout null untuk kontrol manual
        this.setLayout(null);  // Tidak ada layout manager, kontrol posisi manual
        
        // Membuat LabelGambar dan menambahkan ke panel
        // Path gambar sesuai dengan tempat Anda menyimpan gambar
        LabelGambar labelGambar = new LabelGambar("/img/kueView.png");  // Pastikan path gambar relatif yang benar
        
        // Menentukan posisi dan ukuran gambar
        labelGambar.setBounds(0, 0, 794, 526);  // Tentukan posisi dan ukuran gambar sesuai dengan kebutuhan
        
        // Menambahkan LabelGambar ke panel
        this.add(labelGambar);  // Menambahkan label gambar ke panel
        
        // Menentukan ukuran panel
        this.setPreferredSize(new java.awt.Dimension(794, 526));  // Ukuran panel sesuai dengan gambar
    }



    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kueView.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2249, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1045, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
