/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.MasakanRumahan;

import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;


/**
 *
 * @author User
 */
public class viewMasakanRumah extends javax.swing.JPanel {
    private JLabel nameLabel;
    private JTextArea ingredientsTextArea;
    private JTextArea stepsTextArea;
    private JLabel difficultyLabel;
    private JLabel cookingTimeLabel;
    private JLabel ratingLabel;

    public viewMasakanRumah() {
        initComponents();
        initCustomComponents();
    }

    private void initCustomComponents() {
        setLayout(new java.awt.GridBagLayout());
    java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
    gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gbc.insets = new java.awt.Insets(10, 10, 10, 10);

    // Nama Resep
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.gridwidth = 2;
    nameLabel = new JLabel("Nama Resep Tidak Tersedia", JLabel.CENTER);
    nameLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
    add(nameLabel, gbc);

    // Bahan
    gbc.gridy++;
    gbc.gridwidth = 1;
    JLabel ingredientsLabel = new JLabel("Bahan:");
    ingredientsLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
    add(ingredientsLabel, gbc);

    gbc.gridx = 1;
    ingredientsTextArea = new JTextArea("Bahan Tidak Tersedia");
    ingredientsTextArea.setEditable(false);
    ingredientsTextArea.setLineWrap(true);
    ingredientsTextArea.setWrapStyleWord(true);
    add(new JScrollPane(ingredientsTextArea), gbc);

    // Langkah Memasak
    gbc.gridx = 0;
    gbc.gridy++;
    JLabel stepsLabel = new JLabel("Langkah Memasak:");
    stepsLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
    add(stepsLabel, gbc);

    gbc.gridx = 1;
    stepsTextArea = new JTextArea("Langkah Memasak Tidak Tersedia");
    stepsTextArea.setEditable(false);
    stepsTextArea.setLineWrap(true);
    stepsTextArea.setWrapStyleWord(true);
    add(new JScrollPane(stepsTextArea), gbc);

    // Tingkat Kesulitan
    gbc.gridx = 0;
    gbc.gridy++;
    JLabel difficultyTextLabel = new JLabel("Tingkat Kesulitan:");
    difficultyTextLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
    add(difficultyTextLabel, gbc);

    gbc.gridx = 1;
    difficultyLabel = new JLabel("Tidak Tersedia");
    add(difficultyLabel, gbc);

    // Waktu Memasak
    gbc.gridx = 0;
    gbc.gridy++;
    JLabel timeLabel = new JLabel("Waktu Memasak:");
    timeLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
    add(timeLabel, gbc);

    gbc.gridx = 1;
    cookingTimeLabel = new JLabel("Tidak Tersedia");
    add(cookingTimeLabel, gbc);

    // Rating
    gbc.gridx = 0;
    gbc.gridy++;
    JLabel ratingTextLabel = new JLabel("Rating:");
    ratingTextLabel.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
    add(ratingTextLabel, gbc);

    gbc.gridx = 1;
    ratingLabel = new JLabel("Tidak Tersedia");
    add(ratingLabel, gbc);

    }

   public void setRecipeData(String recipeName, String mainIngredients, String cookingSteps, String difficulty, String cookingTime, String rating) {
    System.out.println("Nama Resep: " + recipeName);
    System.out.println("Bahan: " + mainIngredients);
    System.out.println("Langkah Memasak: " + cookingSteps);
    System.out.println("Tingkat Kesulitan: " + difficulty);
    System.out.println("Waktu Memasak: " + cookingTime);
    System.out.println("Rating: " + rating);

    nameLabel.setText(recipeName != null ? recipeName : "Nama Resep Tidak Tersedia");
    ingredientsTextArea.setText(mainIngredients != null ? mainIngredients : "Bahan Tidak Tersedia");
    stepsTextArea.setText(cookingSteps != null ? cookingSteps : "Langkah Memasak Tidak Tersedia");
    difficultyLabel.setText(difficulty != null ? difficulty : "Tingkat Kesulitan Tidak Tersedia");
    cookingTimeLabel.setText(cookingTime != null ? cookingTime : "Waktu Memasak Tidak Tersedia");
    ratingLabel.setText(rating != null ? rating : "Rating Tidak Tersedia");
}
  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recipeDetailPanel = new costum.DetailPanelPoppins();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        recipeDetailPanel.setBackground(new java.awt.Color(255, 255, 255));
        add(recipeDetailPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private costum.DetailPanelPoppins recipeDetailPanel;
    // End of variables declaration//GEN-END:variables
}
