/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.MasakanRumahan;

/**
 *
 * @author User
 */
public class viewMasakanRumah extends javax.swing.JPanel {

    /**
     * Creates new form viewMasakanRumah
     */
    public viewMasakanRumah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recipeDetailPanel = new costum.DetailPanelPoppins();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        recipeDetailPanel.setBackground(new java.awt.Color(255, 255, 255));
        add(recipeDetailPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private costum.DetailPanelPoppins recipeDetailPanel;
    // End of variables declaration//GEN-END:variables
}
